# Generated by Django 5.2.3 on 2025-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=5),
        ),
        migrations.AlterField(
            model_name='applications',
            name='application_status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Under Review', max_length=20),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Prefer not to Say', 'Prefer not to Say')], max_length=18),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_title',
            field=models.CharField(max_length=30),
        ),
    ]
