# Generated by Django 5.2.3 on 2025-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
