services:
  - type: web
    name: jobfinder-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    workingDir: backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.13

  - type: web
    name: jobfinder-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    workingDir: frontend
